[build]
  command = "npm run build"
  publish = "dist/peopletrak"

[[plugins]]
  package = "@netlify/angular-runtime"
  [plugins.inputs]
    packagePath = "."

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_VERSION = "22.21.1"

